### ISSUE TITLE
New icon request - Eyeball

### ISSUE THREAD

**Issue by almilner** [indiana-university/rivet-icons#12]
The purpose of this request would be for previewing items and hiding/showing items. Example coming soon.

**Comment by cnhymer** [comment]
![image](https://user-images.githubusercontent.com/47367585/52300980-464f3380-2957-11e9-978c-ed911d6c85ac.png)

**Comment by levimcg** [comment]
I've pulled this into the backlog. We'll get it planed and worked up asap.

**Comment by basham** [comment]
Please close this issue, @levimcg. The icon is now in the `master` branch.
