### ISSUE TITLE
New icon request - Home

### ISSUE THREAD

**Issue by cnhymer** [indiana-university/rivet-icons#13]
Nicholas requested a home icon for the KB

![image](https://user-images.githubusercontent.com/47367585/52301074-88787500-2957-11e9-981c-254b70b636c0.png)

**Comment by levimcg** [comment]
I've pulled this into the backlog. We'll get it planed and worked up asap.

**Comment by basham** [comment]
Please close this issue, @levimcg. The icon is now in the `master` branch.
