### ISSUE TITLE
New icon- Refresh

### ISSUE THREAD

**Issue by anmaxey** [indiana-university/rivet-icons#16]
Working on an implementation of a refresh/reoccurring icon to be used in the Student Appointment Scheduler.
![reoccuring_icon](https://user-images.githubusercontent.com/12070352/53123846-0a57c900-3528-11e9-97b1-5cbd653a2beb.png)

**Comment by levimcg** [comment]
@anmaxey Good call. This is one we've needed for a while. I've pulled it into the backlog so we can get it planned and prioritized. Thanks! 🙌

**Comment by anmaxey** [comment]
submitted PR #17

**Comment by levimcg** [comment]
Added via #18
