### ISSUE TITLE
Bundle icons as symbols

### ISSUE THREAD

**Issue by scottanthonymurray** [indiana-university/rivet-icons#2]
Some recent work allowed me to experiment with integrating Rivet icons with React.
https://github.iu.edu/iu-uits-es/ess-sisaarex-appointments/pull/3/commits/c094904ed94ee06ad4eab161b7e8ef3528d9af7e

With the ESS Component Library, icons were bundled as SVG strings, stored in the JS, and rendered inline. This provided a lot of flexibility with styling and manipulating the SVG inner as needed. However, that is very specific to a React and Webpack way of doing things.

If wanting to adopt some of the approaches of Rivet, the icons would be best served as an external file. One approach would be to have them all separate.

```
https://assets.uits.iu.edu/css/rivet/0.5.0/rivet-icon-arrow-down.svg
https://assets.uits.iu.edu/css/rivet/0.5.0/rivet-icon-arrow-left.svg
https://assets.uits.iu.edu/css/rivet/0.5.0/rivet-icon-arrow-right.svg
...
```

Then it could be included as this:

```
<img alt="" src="https://assets.uits.iu.edu/css/rivet/0.5.0/rivet-icon-arrow-down.svg" />
```

However, SVG linked via the `<img>` tag means you no longer have the ability to change the default fill color, which is quite limiting.

The approach I settled on is using SVG symbols. This provides the benefit of single external source file that can be styled. This is how it could work:

## 1. Bundle icons into a single SVG.

```
https://assets.uits.iu.edu/css/rivet/0.5.0/rivet-icons.svg
```

```svg
<svg xmlns="http://www.w3.org/2000/svg">
  <defs>
    <symbol id="check-circle-breakout" viewBox="0 0 16 16">
      <path fill="currentColor" d="M8,16A8,8,0,1,1,10.29.33a1,1,0,0,1-.57,1.92A6,6,0,1,0,14,8a1,1,0,1,1,2,0A8,8,0,0,1,8,16Z"/>
      <path fill="currentColor" d="M7.95,11.89a1.26,1.26,0,0,1-.75-.25L3.4,8.8A1,1,0,1,1,4.6,7.2L7.77,9.58,14.18.43a1,1,0,0,1,1.64,1.15L9,11.36a1.25,1.25,0,0,1-.83.52Zm-.62-1.68h0Z"/>
    </symbol>
    <symbol id="chevron-left" viewBox="0 0 16 16">
      <path fill="currentColor" d="M10.5,15a1,1,0,0,1-.77-.36L4.87,8.8a1.25,1.25,0,0,1,0-1.61L9.73,1.36a1,1,0,0,1,1.54,1.28L6.8,8l4.47,5.36A1,1,0,0,1,10.5,15ZM6.41,8.47h0Zm0-1h0Z"/>
    </symbol>
    <symbol id="chevron-right" viewBox="0 0 16 16">
      <path fill="currentColor" d="M5.5,15a1,1,0,0,1-.77-1.64L9.2,8,4.73,2.64A1,1,0,0,1,6.27,1.36L11.13,7.2a1.25,1.25,0,0,1,0,1.61L6.27,14.64A1,1,0,0,1,5.5,15ZM9.6,8.48h0Zm0-1h0Z"/>
    </symbol>
    <symbol id="pencil" viewBox="0 0 16 16">
      <path fill="currentColor" d="M14.62,4.19,11.74,1.34a1.1,1.1,0,0,0-1.55,0L0,11.62,0,16l4.45,0L14.64,5.73A1.1,1.1,0,0,0,14.62,4.19ZM3.62,14H2V12.44l6-6L9.58,8ZM11,6.57,9.4,5,11,3.4,12.57,5Z"/>
    </symbol>
    <symbol id="plus" viewBox="0 0 16 16">
      <path fill="currentColor" d="M14,7H9V2A1,1,0,0,0,7,2V7H2A1,1,0,0,0,2,9H7v5a1,1,0,0,0,2,0V9h5a1,1,0,0,0,0-2Z"/>
    </symbol>
  </defs>
</svg>
```

Notice: I've found no affect by including or not including `width` and `height` attributes in SVG symbols, so they can probably be removed.

## 2. Add some CSS so it keeps the right size.

```css
.rvt-icon {
  height: 1rem;
  width: 1rem;
}
```

## 3. Reference with symbols.

```html
<button className="rvt-button rvt-button--plain" title="Next">
  <span className="rvt-sr-only">Next</span>
  <svg className="rvt-icon" aria-hidden="true">
    <use xlink:href="https://assets.uits.iu.edu/css/rivet/0.5.0/rivet-icons.svg#chevron-right"></use>
  </svg>
</button>
```

## 4. React projects could simplify integration with a component.

```jsx
function Icon(props) {
  const { name, src = 'https://assets.uits.iu.edu/css/rivet/0.5.0/rivet-icons.svg' } = props
  return (
    <svg className="rvt-icon" aria-hidden="true">
      <use xlinkHref={`${src}#${name}`}></use>
    </svg>
  )
}
```

```jsx
<button className="rvt-button rvt-button--plain" title="Next">
  <span className="rvt-sr-only">Next</span>
  <Icon name="chevron-right" />
</button>
```

## 5. Use a polyfill for IE

This [external resource method does not work for IE](https://css-tricks.com/svg-use-external-source/), but a the [`svg4everybody` polyfill](https://github.com/jonathantneal/svg4everybody) (`2kb`) could be recommended in that case.

**Comment by basham** [comment]
lmcgrana commented on Apr 4, 2018

***

This is a good conversation to start having. The single bundled SVG icon is interesting for sure. I'm wondering how big (KBs) that single SVG might get over time as we add more icons to the set? This React solution is really nice. 👌

I know a lot of folks are used to something like FontAwesome which makes it really easy to include icons with minimal markup. I don't really think an icon font is the way forward, but I'm wondering how we might implement something that is as easy to use.

This icon library, Feather, has some pretty cool features around usage. Especially this script that allows the same functionality as something like FontAwesome, except without the weight of an entire icon font.

https://github.com/feathericons/feather#client-side-javascript

Good stuff to be thinking about. Thanks for sharing!

**Comment by basham** [comment]
csbasham commented on Apr 4, 2018

***

Some articles about font icons verses SVG icons (mostly from 2–3 years ago):

- https://css-tricks.com/icon-fonts-vs-svg/
- https://www.sitepoint.com/icon-fonts-vs-svg-debate/
- https://bulldogjob.com/articles/626-svgs-vs-icon-fonts-the-battle-without-resolution
- https://cloudfour.com/thinks/seriously-dont-use-icon-fonts/
- https://benfrain.com/seriously-use-icon-fonts/
- https://speakerdeck.com/ninjanails/death-to-icon-fonts
- https://blog.github.com/2016-02-22-delivering-octicons-with-svg/
- https://www.ianfeather.co.uk/ten-reasons-we-switched-from-an-icon-font-to-svg/

> I'm wondering how big (KBs) that single SVG might get over time as we add more icons to the set?

Some of the articles above suggest font icons have perhaps a 25% space savings, but I wonder if the SVG was optimized.

> I don't really think an icon font is the way forward, but I'm wondering how we might implement something that is as easy to use.

Agreed. However we go about it, it would be good to set up a pattern for extension. So, if projects need their own icons, they should be able to do something similar to Rivet and have it work well with Rivet. If we went the way of icon fonts, that would increase the difficulty of other teams introducing custom icons, if they suddenly needed to manage their own font files as well.

> This icon library, Feather, has some pretty cool features around usage.

Yes, that's a good exemplar. Their JS solution is interesting, but it still bundles every SVG into a JS file.

**Comment by basham** [comment]
csbasham commented on Apr 4, 2018

***

As for the SVG bundle size, if a team wants a subset of the icons, with perhaps some of their own, maybe there's some sort of script that could be included in the rivet-icons package that will output a bundled and optimized sprite. For example:

```js
import { svgsToSprite } from 'rivet-icons'

const source = [
  // Reference Rivet icons by name
  'check-circle-breakout',
  'chevron-left',
  'chevron-right',
  'pencil',
  'plus',
  // Reference all custom icons in a folder.
  './src/icons1/',
  // Reference one custom icon by path.
  // Symbol name is derived from the file name.
  './src/icons2/custom-icon.svg',
  // Reference one custom icon by path with custom symbol name.
  // What's better: `name` or `id`?
  { name: 'map', path: './src/icons2/custom-icon2.svg' }
]
const config = {
  output: './dist/icons.svg'
  // Other options that may be needed.
}
svgsToSprite(source, config)
```

Maybe that's run as a npm script. Maybe we create a Webpack plugin to do it at compile-time.

**Comment by basham** [comment]
Here's another option, if wanting to use background images and [CSS variables (supported in all browsers but IE)](https://caniuse.com/#feat=css-variables).
https://medium.com/@adactio/inlining-svg-background-images-in-css-with-custom-properties-c32adde256c3

Instead of:

```css
.myComponent {
    background-image: url('data:image/svg+xml;utf8,<svg> ... </svg>');
}
.myComponent--variant {
    background-image: url('data:image/svg+xml;utf8,<svg> ... </svg>'), url('data:image/svg+xml;utf8,<svg> ... </svg>');
}
```

You can do this:

```css
:root {
    --firstSVG: url('data:image/svg+xml;utf8,<svg> ... </svg>');
    --secondSVG: url('data:image/svg+xml;utf8,<svg> ... </svg>');
}

.myComponent {
    background-image: var(--firstSVG);
}
.myComponent--variant {
    background-image: var(--firstSVG), var(--secondSVG);
}
```
