### ISSUE TITLE
New Icon Requests: 'star' and 'slash'

### ISSUE THREAD

**Issue by christiemh54** [indiana-university/rivet-icons#29]
We use the star and slash icons to represent positive and negative service indicators in AdRx. These are carry over icons that are widely recognized by AdRx and SIS users.

![image](https://user-images.githubusercontent.com/47330881/55903291-51af1d00-5b9b-11e9-8df2-44e53961cda4.png)

**Comment by basham** [comment]
Following conventions I'm noticing in the current icon set, I think `star` should be an outlined version of the star. If wanting a solid version, that would probably be called `star-solid`.

Given stars could be used for favoriting or rating things, I feel like both versions could be useful, even if AdRx just needs one of them.

The slash icon should probably be called `ban`.

**Comment by christiemh54** [comment]
@levimcg @basham (I couldn't find Cody to tag)
Nat would like to get this released with our student summary page for AdRx in the next sprint, so if any of you have time and could get these icons completed by May 13, that would allow us to do that. Thanks!

**Comment by basham** [comment]
@levimcg I may have some time this Friday to work on this issue. However, that may mean that this work will need to be merged before your #33 PR, in order for the icons to be ready for @christiemh54's requested deadline. I assume that should be okay with you?

**Comment by levimcg** [comment]
Yep, totally fine, do what you need to do, and I'll pull in any changes if I can't get my PR finished before. 👍

**Comment by basham** [comment]
@christiemh54 The `ban`, `star`, and `star-solid` icons are now available in the `master` branch and viewable in the [icon set demo](https://indiana-university.github.io/rivet-icons/).

**Comment by basham** [comment]
@levimcg Please close this issue.

**Comment by christiemh54** [comment]
@basham looks great, thank you for getting it done this week!
