### ISSUE TITLE
Caution icon request

### ISSUE THREAD

**Issue by scottanthonymurray** [indiana-university/rivet-icons#3]
At present there is only the "exclamation", and perhaps the close-circle icons that can be used to represent "caution" and "error" respectively, I think these are situations that might warrant their own icon. 

![image](https://github.iu.edu/storage/user/1221/files/dbf5d178-3ca4-11e8-91be-e27aacebb893)

In a recent mock-up @tbazler had the following to denote an error. 
![image](https://github.iu.edu/storage/user/1221/files/f8ecfa40-3ca4-11e8-851e-826566fc8c09)

Upon further thought, I've also considers a slight change to the success check such that the three are consist. 
![image](https://github.iu.edu/storage/user/1221/files/6a536976-3ca5-11e8-91fc-28965663bbee)

But I definitely would preferring not making that decision for myself. 

Info-Circle added to screen-cap for verbosity. 
![image](https://github.iu.edu/storage/user/1221/files/0e5b34fe-3ca6-11e8-91a0-4987d2f1d0c6)

**Comment by nbannist** [comment]
I think some systems use something similar to the "Do Not Enter" road sign (circle with a partial line along the equator) if we want to not overload the "x" since that's also used for "close". Just a thought.
