### ISSUE TITLE
New icon: gears

### ISSUE THREAD

**Issue by lanebowman** [indiana-university/rivet-icons#32]
Something like this: https://thenounproject.com/search/?q=gears&i=683134

**Comment by basham** [comment]
`gear` is already an icon.

![Gear icon](https://user-images.githubusercontent.com/347558/57482541-e1b3b580-7272-11e9-92ab-a97dddfea9ed.png)


Demo: https://indiana-university.github.io/rivet-icons/
SVG: https://github.com/indiana-university/rivet-icons/blob/develop/src/svg/rvt-icon-gear.svg

Is that what you were looking for? Or do you specifically want multiple gears? If multiple, that may get really challenging to fit in `16px` square resolution.

**Comment by lanebowman** [comment]
Yeah, I've got a team asking for multiple gears--and I explained it'll be difficult to even get 2 inside of 16px.

**Comment by levimcg** [comment]
This was released in version [0.3.0](https://github.com/indiana-university/rivet-icons/releases/tag/v0.3.0)

Demo here: https://indiana-university.github.io/rivet-icons/#rvt-icon-gears
