### ISSUE TITLE
ESPD team additional icons

### ISSUE THREAD

**Issue by thrclark** [indiana-university/rivet-icons#55]
The ESPD team has extended the base Rivet icon set with 11 new icons that we use in some of our components and designs. Sharing this here in the case that any of these icons could be useful to the greater Rivet community.

The additional icons can be seen here:
https://espd.sitehost.iu.edu/rvb/develop/php/lib-extra-icons.php

Some example usages:
https://espd.sitehost.iu.edu/rvb/develop/php/lib-extra-richtext.php
https://espd.sitehost.iu.edu/int/master/php/verification.php

I can create a PR if any of these icons are of value to the community.

**Comment by lanebowman** [comment]
@thrclark, I'd really like to use the database icon. @illusivesunrae, is there consideration of the ESPD icons being pulled in?

Also, you don't happen to have an icon for a browser or window, do you?
