### ISSUE TITLE
Icon request: Trash

### ISSUE THREAD

**Issue by scottanthonymurray** [indiana-university/rivet-icons#6]
It's not yet totally settled, but we may want to use a trash icon in AdRx Reminders, to delete a reminder. Perhaps a trash icon could be added. Lots of simple options:
https://thenounproject.com/search/?q=trash

Alternatively or in the meantime, we will use the **close** or **close circle** icons.

**Comment by levimcg** [comment]
This was added via #7 Closing this issue 👍
