### ISSUE TITLE
Megaphone icon

### ISSUE THREAD

**Issue by cwthomps** [indiana-university/rivet-icons#61]
I'd like to get a megaphone icon in the library, which I'll be using on the mobile app. I've included an image of one I've created in the Rivet style. If you'd like to use it verbatim, let me know and I'll pass along vector art.

![image](https://user-images.githubusercontent.com/35814544/80250587-22ead400-8642-11ea-8f72-2a0dc8c42ca4.png)

**Comment by levimcg** [comment]
This was released in [0.6.0](https://github.com/indiana-university/rivet-icons/releases/tag/v0.6.0) 📢  ✅
