### ISSUE TITLE
Inbox icon

### ISSUE THREAD

**Issue by lanebowman** [indiana-university/rivet-icons#84]
Hi, I'd like to request an "inbox" icon (see below). Or, something that would indicate that there's an outstanding task that needs completed. A completed state, maybe a checkbox inside the inbox, would also be desired. Thanks!

![image](https://user-images.githubusercontent.com/18720960/125355052-8853df00-e332-11eb-951a-380214b4ff74.png)

**Comment by levimcg** [comment]
Thanks @lanebowman We're working on some pretty big updates to the icons, including a handful of new icons, so we'll get this added to the list of new ones 👍🏻
